### ISSUE TITLE
Example build fails on MacOS with python2

### ISSUE THREAD

**Issue by ivirshup** [maximilianh/cellBrowser#40]
Similar to #35, running the example build command throws an error. Here's the traceback:

```python2
Traceback (most recent call last):
  File "../../src/cbBuild", line 9, in <module>
    cellbrowser.convertAndCopyCli()
  File "../../src/cbPyLib/cellbrowser.py", line 2393, in convertAndCopyCli
    convertAndCopy(confFnames, outDir, port)
  File "../../src/cbPyLib/cellbrowser.py", line 2364, in convertAndCopy
    convertDataset(inConf, outConf, datasetDir)
  File "../../src/cbPyLib/cellbrowser.py", line 2131, in convertDataset
    convertExprMatrix(inConf, outMatrixFname, outConf, sampleNames, geneToSym, datasetDir, needFilterMatrix)
  File "../../src/cbPyLib/cellbrowser.py", line 1827, in convertExprMatrix
    copyMatrixTrim(matrixFname, outMatrixFname, metaSampleNames, needFilterMatrix)
  File "../../src/cbPyLib/cellbrowser.py", line 1430, in copyMatrixTrim
    matIter.open(inFname)
  File "../../src/cbPyLib/cellbrowser.py", line 663, in open
    encoding='utf-8',
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

From what I can tell, this is caused by having the shebang of `cbBuild` call for `python2` to be used and the usage of [`encoding` as an argument](https://github.com/maximilianh/cellBrowser/blob/ace4d882f99bb6034219bc75f9230141741d3b3e/src/cbPyLib/cellbrowser.py#L663) to `subprocess.Popen`, as introduced by #36. In my `python v2.7.15` installation, `subprocess.Popen` does not have an `encoding` argument:

```python2
>>> inspect.getargs(subprocess.Popen.__init__.__code__)
Arguments(args=['self', 'args', 'bufsize', 'executable', 'stdin', 'stdout', 'stderr', 'preexec_fn', 'close_fds', 'shell', 'cwd', 'env', 'universal_newlines', 'startupinfo', 'creationflags'], varargs=None, keywords=None)
```

I can get around this error by using:

```bash
$ python3 ../../src/cbBuild -o ~/public_html/cb/ -p 8888
```

**Comment by maximilianh** [comment]
Yes, this was caused by yesterday's PR from someone else. I had tested it
only on python3.  I'll change the python version in the shebang and also
this particular line.

**Comment by ivirshup** [comment]
You're totally right, I must have been looking at `cellbrowser.py` on ace4d882f9. In general though, homebrew sets a symlink for `python->python3`, so that's probably why python2 was being used for me.

**Comment by maximilianh** [comment]
I certainly strive to make at least cbBuild work with both python2 and
python3, so thanks for opening this ticket. I'm closing it now as the issue
is hopefully solved. Let me know if you run into any other issues.

Good to know about homebrew having python3 as the default. ArchLinux is the
same, most other linux distros will keep python2 as the default for a while.
